name: Generate Calendar

permissions:
  contents: write

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  generate-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Bloomington
      run: |
        python cal.py --generate --year $(date +%Y) --month $(date +%m) --timezone "America/Indiana/Indianapolis"

    - name: Copy output to bloomington folder
      run: |
        cp $(date +%Y-%m).html ./bloomington/

    - name: Commit and push if changes
      env:
        GITHUB_TOKEN: ${{ secrets.COMMUNITY_CALENDAR }}
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate calendar" && git push)